### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'offset' in undefined

### ISSUE THREAD

**Issue by jrfii** [beyonk-adventures/svelte-mapbox#32]
If I set "popup = true," my markers do not render and I get: "TypeError: Cannot use 'in' operator to search for 'offset' in undefined." However, if I set "popup = false," my markers render, but without a popup. 

Oddly, the popups work in a development environment, but they fail in a production environment. I'm using Heroku and have set "NPM_CONFIG_PRODUCTION = false"; is it possible that this is causing the error? I've been trying to fix this for two and a half months. Please advise.

**Comment by antony** [comment]
`popup=true` is the default, so if you try the demo app, you can tell that it works.

`NPM_CONFIG_PRODUCTION` has no bearing on whether this library works at all, it doesn't know anything about that environment variable name.

I'm not sure why it is failing on your production environment - but it is something specific to the way you're building or setting up your application, and wouldn't be specific to this library per-se.

I would suggest debugging the issue in the browser console to find out the root cause - i.e. what is it trying to search for `offset` in.

**Comment by jrfii** [comment]
Antony,
First, thank you for your quick response, but also thank you for all of your contributions to Svelte and the greater community.
As a neophyte, I'm still struggling with debugging in a production environment. The error is being thrown from a node module, if I recall correctly, map.js line 322. I thought this was a part of the @beyonk/svelte-mapbox library, but I'll have to take a closer look.
Sorry to clutter up your library's Issue section!
Best regards,
John

**Comment by antony** [comment]
No worries, it's certainly an odd one. I couldn't be sure what is causing that specific error - I don't know what the hosting environment would have to do with the error you are seeing.

Sorry I can't be of more help!

**Comment by antony** [comment]
I've basically rewritten this module now! If the error still occurs after upgrading to > 8.0.3 please comment and we can reopen.
